version: '3.8'

services:
  server:
    build:
      context: ./chatbox_backend
      target: final
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chatbox
    depends_on:
      - mongodb
    develop:
      watch:
        - path: ./chatbox_backend
          target: /app
          action: sync
        - path: ./chatbox_backend
          action: rebuild

  web:
    build: ./chatbox_frontend
    ports:
      - 5173:5173
    depends_on:
      - server
    develop:
      watch:
        - path: ./chatbox_frontend/package.json
          action: rebuild
        - path: ./chatbox_frontend/package-lock.json
          action: rebuild
        - path: ./chatbox_frontend
          target: /app
          action: sync

  mongodb:  
    image: mongo:latest  
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=chatbox
    volumes: 
      - mongo-data:/data/db
    ports: 
      - 27017:27017

volumes: 
  mongo-data:
